runtime: nodejs16
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
env: standard

handlers:
- url: /(.*\.css)
  static_files: dist/my-app/\1
  upload: dist/my-app/.*\.css
  mime_type: text/css
  expiration: "10m"

- url: /(.*\.js)
  static_files: dist/my-app/\1
  upload: dist/my-app/.*\.js
  mime_type: application/javascript
  expiration: "10m"

- url: /(.*\.(ico|jpg|png|svg))
  static_files: dist/my-app/\1
  upload: dist/my-app/.*\.(ico|jpg|png|svg)
  mime_type: image/\2
  expiration: "10m"

- url: /(.*\.(woff|woff2|ttf))
  static_files: dist/my-app/\1
  upload: dist/my-app/.*\.(woff|woff2|ttf)
  mime_type: font/\2
  expiration: "10m"

- url: /.*
  static_files: dist/my-app/index.html
  upload: dist/my-app/index.html
